fix the numNodes method
Pay-Ease/graph-json pull request #1
Opened 2017-02-13 22:37 UTC by sjt003

2017-02-13 22:40 UTC, sjt003 reviewed
I approve

2017-02-13 22:40 UTC, mikenichols requested changes

2017-02-13 22:40 UTC, mikenichols commented on lib/graph.js
> +    return this.nodes.length;
Is there a test for this/can we write one?

2017-02-14 17:10 UTC, mikenichols approved these changes
LGTM 👍

2017-02-14 17:43 UTC, letsgetrandy approved these changes

2017-02-14 21:42 UTC, kmwhite approved these changes

2017-02-14 21:42 UTC, merged